# Generated by Django 4.0.3 on 2022-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='philosophers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя философа')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия философа')),
                ('philosophy_name', models.CharField(max_length=100, verbose_name='Философия')),
                ('philosophy', models.TextField(verbose_name='Суть философий')),
                ('birth_time', models.DateField(verbose_name='День рождения')),
                ('death_time', models.DateField(verbose_name='День смерти')),
            ],
        ),
    ]
