# Generated by Django 4.0.3 on 2022-03-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Philosophy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.AlterModelOptions(
            name='philosophers',
            options={'verbose_name': 'Философия', 'verbose_name_plural': 'Философий'},
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя философа')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия философа')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('birth_time', models.DateField(verbose_name='День рождения')),
                ('death_time', models.DateField(verbose_name='День смерти')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Philosophy.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Личность',
                'verbose_name_plural': 'Личности',
            },
        ),
    ]
