# Generated by Django 4.0.3 on 2022-03-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Philosophy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='philosophy_ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philosophy_idea_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='philosophers',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Philosophy.philosophy_ideas'),
        ),
    ]
